### PR TITLE
Map type selection component

### PR DESCRIPTION
**Pull request by visitharri**

### CODE REVIEW

**Comment by visitharri** [comment]
Still no links here, but drop down menu items have been created

**Comment by visitharri** [comment]
I am not the best in CSS. I am trying to put everything in the right position on the page, but I was not totally successful even after few hours of trying. For me CSS is bigger nightmare than coding.

**Comment by visitharri** [comment]
Visuals of the component created. The logic to change the map type will be implemented later.

**Review by kemm0 — CHANGES_REQUESTED** [review]
Using PNG images in the UI should be avoided. We have the react-icons library, and it includes both a Tick icon and a Globe icon. Those should be used instead. You can find all icons that are available from the library here https://react-icons.github.io/react-icons. Especially we shouldn't have an empty image. You can use CSS to keep the indentation same even if there is no image

https://www.npmjs.com/package/react-icons Here's some instructions how to use the icons from react-icons library. Also those have been used in our navbar, so you can look at some reference there.

**Review by kemm0 — APPROVED** [review]

**Pull request merged**
